apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: pod-a
spec:
  containers:
    - name: pod-a
      image: pod-a
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
