apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-b
  template:
    metadata:
      labels:
        app: pod-b
    spec:
      containers:
        - name: pod-b
          image: pod-b
          imagePullPolicy: Never
          env:
            - name: POD_A_BASE_URL
              value: http://pod-a-service:8080
          ports:
            - containerPort: 8080
